### ISSUE TITLE
Project Ideation Suggestion #1

### ISSUE THREAD

**Issue by Ankit-177** [Ankit-177/cpt_project#2]
### College Application Helper/Tracker

Name ideas: AdmitTrack, CollegeCompass, AppAlly, AppSync, AdmitEase, AdmitMap, CollegeApp Scout

- This is an application that allows users to log in and create individual profiles using a JWT login system.
- Each user can create a list of colleges that they plan to apply to
- When a college is clicked on, it redirects the user to their application for that particular college, where they are allowed to create a tasks list and (maybe) track their finances and financial aid status
- We could integrate an AI chatbot (using ChatGPT's API) on the home page to provide college application tips and tricks.

**Comment by wl0503** [comment]
- Not only just basic user information, a JWT login system needs to include the college information students are trying to apply, and their assigned tasks which are only shown by project creators; a JWT login system basically tracks everything that user does in the website
- In AI chatbot, types of questions are given to users before asking question. For example, when they start to operate the chatbot, it says choose question you will ask and show question section such as their financial aid status, and their remaining task. In other words, asking unrelated stuffs are refrained in the first place. 
- Webpage also has a feature that shows the best strategy of going to the particular school for student once they choose college.

**Comment by sfremy** [comment]
Remy
- College List redirect options (read from dataset of stored urls?)
- Task List (custom length text item set?)
- Tracking finances and aid status if possible (just a numerical FAFSA calculator?)

**Comment by Ankit-177** [comment]
Ankit

- JWT login page with backend and frontend
   - Handle API creation with endpoints along with login/sign-up UI
- General frontend features/styling
